### PR TITLE
Add support for Vanilla Forums

### PR DESCRIPTION
**Pull request by jfarthing84**

### CODE REVIEW

**Comment by niksamokhvalov** [comment]
Hi, write test, please. Example:
https://github.com/composer/installers/blob/master/tests/Composer/Installers/Test/InstallerTest.php#L87
https://github.com/composer/installers/blob/master/tests/Composer/Installers/Test/InstallerTest.php#L215

**Comment by jfarthing84** [comment]
Done.

**Comment by niksamokhvalov** [comment]
This branch has conflicts, you need merge master.

**Comment by jfarthing84** [comment]
Rebased off of current master.

**Comment by niksamokhvalov** [comment]
@jfarthing84 your tests failed.

**Comment by jfarthing84** [comment]
Fixed.

**Pull request merged**
