### PR TITLE
plentymarkets custom installer

### PR DESCRIPTION
**Pull request by ChristianMoll**
Created [plentymarkets](https://www.plentymarkets.co.uk/) custom installer for [plentymarkets plugin](http://showcase.plentymarkets.com/)
packages.

### CODE REVIEW

**Comment by ChristianMoll** [comment]
Hello @niksamokhvalov could you merge this commit please?

Best regards,
Christian

**Comment by niksamokhvalov** [comment]
Thanks!

**Comment by niksamokhvalov** [comment]
@ChristianMoll could you checkout the code according to [PSR-2](http://www.php-fig.org/psr/psr-2/)?

**Comment by ChristianMoll** [comment]
@niksamokhvalov Thanks for the reply. I changed the formatting to PSR-2 style.

**Pull request merged**
