### PR TITLE
Add concrete5-core

### PR DESCRIPTION
**Pull request by fabian**
This adds the installer type `concrete5-core` to support the installation of concrete5 (version 5.7+) via Composer as discussed in https://github.com/concrete5/concrete5-5.7.0/issues/360.

The idea is similar to what Drupal is doing with `drupal-core`, but instead to `core/` concrete5 is always installed to `concrete/`.

I will create a separate PR in the concrete5 repository to adjust the composer.json file.

### CODE REVIEW

**Comment by shama** [comment]
I'd like to persuade you against this as I personally don't think `core` types are a good idea.

Only 1 package can own the `concrete/` folder. Bad things will likely happen if more than 1 package has the `concrete-core` type.

Since `core` type folder paths are for framework itself, a much better solution is to use a custom installer or modify the framework itself to load from the native `vendor-dir`.

If you still want a `concrete-core` type despite this warning, I'll merge but I will be pinging you when users run into issues regarding this :)

**Comment by Remo** [comment]
I see that point, but theoretically with concrete5 we could have multiple cores and use the (existing) configuration to point to the one we want to use. @fabian we'd have to go with the update folder too, not sure how that would work, any ideas?

**Comment by fabian** [comment]
Thanks for raising your concerns @shama! Given Drupal is doing the same https://github.com/composer/installers/pull/208#issuecomment-69383573 and concrete5 poses the same problems, I thought this way would be considered best practice. Understand now it's not.

@Remo good point about the update folder - maybe we don't need `concrete5-core` at all and just use the existing `concrete5-update`. Will draft up another PR over at concrete5 for that.

**Comment by fabian** [comment]
@shama  We're just having a discussion over at https://github.com/concrete5/concrete5-5.7.0/pull/2087#issuecomment-83448352 about adding the version of the dependency to the install path - what's your thought about that?

So we could modify [Concrete5Installer](https://github.com/composer/installers/blob/master/src/Composer/Installers/Concrete5Installer.php) to use something like `updates/{$name}/{$version}`.

The downside I see is after a version upgrade the old version folder would be left over.

**Comment by shama** [comment]
:+1: Thanks!

Re: `{$version}` in the path. I don't see any issues but IMO probably not necessary unless users can run multiple cores simultaneously. I think if they need to switch versions they'd just modify their `composer.json` and update.

**Comment by Remo** [comment]
@shama no, you can't run multiple cores, it's just because it's the way concrete5 used to work and maybe some concrete5 users would feel more comfortable this way. It allows you to switch back to an older core without fetching a few thousand files. That's probably the only benefit! All at the cost of having lots of unused files..

@fabian having thought about this again I don't see much benefit of having a version there. Those who work with composer should be able to fetch or backup an older core, shouldn't they?

**Comment by fabian** [comment]
Yeah I think we can agree it's not worth having the version.

**Comment by niksamokhvalov** [comment]
@fabian it's actual? : )

**Comment by fabian** [comment]
@niksamokhvalov Thanks for checking!

Installation of the concrete5 core with Composer is still an unsolved issue but there's also still ongoing discussions at concrete5 how to solve it. So please don't merge this PR yet.

Partially depends on what happens with https://github.com/concrete5/concrete5/issues/3311.

I will update here once concrete5 version 8.0.0 is progressing. If you want to keep only PRs which are ready to merge open feel free to close this PR and I will reopen it once it gets relevant again.

**Comment by niksamokhvalov** [comment]
OK, open this PR, when the time comes.

**Comment by KorvinSzanto** [comment]
@fabian @Remo is this still something worth doing?

**Comment by fabian** [comment]
@KorvinSzanto `concrete5-core` would only make sense if https://github.com/concrete5/concrete5/tree/develop/concrete was published as a Git subtree with its own composer.json - which I don't think any plans exist for.

Personally I'm using `concrete5-update` with a [custom Composer repository](https://github.com/worldskills/concrete5-repository/blob/gh-pages/packages.json) to install concrete5 ZIP distributions. Having `"type": "concrete5-update"` added to https://github.com/concrete5/concrete5 would still be great to allow installation of concrete5 from GitHub with this method. Should I send another PR for that to `concrete5/concrete5`?

**Comment by KorvinSzanto** [comment]
@fabian to be honest I'm not following the discussion very closely since we got composer.json into the repo root. As far as I'm aware we can currently get concrete5 pulled down (at least dev-master so far) using `composer create-project concrete5/concrete5` and you can install using the `./concrete/bin/concrete5 c5:install` command.

Is this pull request only to enable the full process of pulling code AND running a complete installation? Or is it just to facilitate getting a copy of concrete5? If it's the former I'd say probably not worth the effort. If the latter, can you explain how?

Now the subtree split idea, that's not a bad one. It'd be relatively easy to do and I can imagine some benefit coming from it.

**Pull request closed without merging**
