### PR TITLE
Add WordPress dropin support

### PR DESCRIPTION
**Pull request by bueltge**
WordPress alows to replace some functions with Dropins.
This small change in the commit allow to add via composer the dropin.

Below is a table with all Dropins I know or I have found. The possible Dropins are echoing via the function `_get_dropins()`.

| FILE | TYPE OF DROPIN | ACTIVE SINCE | CONTEXT |
| --- | --- | --- | --- |
| advanced-cache.php | Advanced or Alternative Cache | Constant WP_CACHEis TRUE | Single Installation |
| db.php | Own database class | Always | Single installation |
| db-error.php | Own database error alert | At DB Error | Single installation |
| install.php | Own installation routine | At installation | Single installation |
| maintenance.php | Own maintenance message | At updates, maintenance | Single installation |
| object-cache.php | External Object Cache | Always | Single installation |
| sunrise.php | Before the WP Multisite Installation gets loaded | If constant SUNRISEset | Multisite installation |
| blog-deleted.php | Own message, when a blog gets deleted | If a blog gets deleted | Multisite installation |
| blog-inactive.php | Own message, if a blog is set inactive | If a blog becomes inactive | Multisite installation |
| blog-suspended.php | Own message, if a blog got suspended | When a blog gets marked as archive or spam | Multisite installation |
| $locale.php | functions at active language key | When language key set in constant WP_LANG | Single & multisite installation |

### CODE REVIEW

**Comment by johnpbloch** [comment]
:+1: would love to see this. It might also make sense to look for these files in the package (maybe with a composer.json `extra` override hash?) and manage them directly as part of the install/update/delete process.

**Comment by slbmeh** [comment]
I'm not sure it's feasible to add drop-in support to this project.  Drop-ins are single files, and composer installs a directory of files and dependencies.

**Comment by bueltge** [comment]
Same idea, new pull request, but redundant - #288

**Comment by bueltge** [comment]
@slbmeh Tis should work. Composer have the feature, but is not documented.
see https://github.com/composer/composer/issues/946
`"type": "file"`

**Comment by pySilver** [comment]
@bueltge i'm not sure I got you right. Where exactly `"type": "file"` should go? To my drop-in? It already has `wordpress-dropin` type ...

**Comment by bueltge** [comment]
This type is for the dist parameter.
```json
"dist": {
    "type": "file",
    "url": "path/to/file"
},
```

like this context

```json
    "repositories": [
    {
        "type": "package",
        "package": {
            "name": "user/repo-dropin",
            "type": "wordpress-dropin",
            "version": "1.5",
            "dist": {
                "type": "file",
                "url": ""
            },
            "require": {
                "composer/installers": "v1.0.7"
            }
        }
    }
```

Sorry, I haven't currently a project or access to a topic. Also I haven't currently possibilities to work with composer, a client behind a proxy.

**Pull request merged**
