### PR TITLE
Added Maya module definition with tests

### PR DESCRIPTION
**Pull request by spescina**

### CODE REVIEW

**Comment by alcohol** [comment]
Should Maya not be added into [src/Composer/Installers/Installer.php](/composer/installers/tree/master/src/Composer/Installers/Installer.php) ?

**Comment by spescina** [comment]
Yes, I think you're right. I'm going to change the file. Should I submit a new PR after?

**Comment by alcohol** [comment]
I don't think you can re-open this one, so yes a new PR.

**Comment by spescina** [comment]
done.

#342

**Pull request merged**
