### PR TITLE
Fix Drupal Core (drupal-core) install location

### PR DESCRIPTION
**Pull request by RobLoach**
@davidbarratt Congrats on getting `drupal-core` working. This right?

### CODE REVIEW

**Comment by davidbarratt** [comment]
@RobLoach looks good to me! :)

**Comment by shama** [comment]
I still think a type installing to a single folder is weird. Merging and crossing my fingers.

**Comment by davidbarratt** [comment]
I mean you could change it to `{$name}/` if you wanted to (since the name is `core`), but I think that's weirder.

**Comment by shama** [comment]
@davidbarratt Oh? If we can, then we should. I'm concerned about multiple packages with a type conflicting with each other.

**Comment by davidbarratt** [comment]
@shama yeah I don't see why you couldn't... here's the composer file:
https://github.com/drupal/drupal/blob/8.0.x/core/composer.json#L2

and it needs to be put in the `core` folder in the root.

That should work right @RobLoach ?

**Comment by RobLoach** [comment]
> I mean you could change it to {$name}/ if you wanted to (since the name is core), but I think that's weirder.

Let's brainstorm some of the possible use cases for `drupal-core`...

1. **Drupal core**
2. **Distributions**, like [OpenAtrium](https://www.drupal.org/project/openatrium)?
  If OpenAtrium's `composer.json`'s name is declared as `drupal/openatrium`, and its type is `drupal-core`, then using `{$name}/`, will install into `openatrium/`. Is that the desired effect?
3. **Drupal forks**, I could see people running a maintained fork of Drupal for a few patches that you want rolled in, and naming it something other than `drupal/core`. `drupal/AwesomeEdition`? Possibility, but still you wouldn't want it installed into `/AwesomeEdition/`, you'd still want your version of Core installed into `/core/`.

Thoughts?

**Comment by davidbarratt** [comment]
@RobLoach,

I agree, since anything of type `drupal-core` *must* be in the `/core` directory (and no where else) then you are correct, using `/{$name}` doesn't make any sense because it would only then work for the official drupal core.

**Comment by shama** [comment]
Alright, I'll leave it as is then.

Hopefully people just don't publish a bunch of packages with the `drupal-core` type. Otherwise that user with multiple core types in their deps is going to have a fun time trying to figure out why things are broken.

**Comment by davidbarratt** [comment]
@shama,

yeah I hear you.. I just don't know what else you would do since Drupal core is required to be in `/core`. :/ Hopefully if they are using composer they are smart enough to figure that out.

**Comment by davidbarratt** [comment]
@shama 

Could you tell me what the next release this PR will be a part of?

I'm working on https://www.drupal.org/node/2373197 and I realized that since we have minimum stability set to `dev` setting the version with the caret operator works now, but I'd need to know what the first release it will be part of will be (if you know).

Is it safe to assume 1.0.20?

**Comment by shama** [comment]
Yep! Just pushed a tag for `1.0.20`. Thanks!

**Comment by davidbarratt** [comment]
Thanks!

I've updated the patch in https://www.drupal.org/node/2373197
@RobLoach would you mind testing? Thanks!

**Pull request merged**
