### PR TITLE
Fix install location for CakePHP 3.x plugins.

### PR DESCRIPTION
**Pull request by ADmad**
I think this is a better fix than #218

### CODE REVIEW

**Comment by shama** [comment]
Thanks!

**Comment by shama** [comment]
@ADmad @AD7six Any idea why travis is failing? https://travis-ci.org/composer/installers/jobs/51259252

**Comment by shama** [comment]
It passes locally for me.

**Comment by ADmad** [comment]
@shama It passes locally for me too. It seems on line 41 of CakePHPInstaller `$this->composer->getConfig()->get('vendor-dir')` returns `/vendor` instead of `vendor`.

**Pull request merged**
