### PR TITLE
Switch to PSR-4

### PR DESCRIPTION
**Pull request by RobLoach**
https://getcomposer.org/doc/04-schema.md#psr-4

### CODE REVIEW

**Comment by TomasVotruba** [comment]
In what state is this? I think I can finish it, if needed.

**Comment by shama** [comment]
@TomasVotruba It needs merge conflicts resolved and tests passing.

**Comment by RobLoach** [comment]
Don't even believe this is needed. PSR-0 is working fine. Closing.

**Comment by TomasVotruba** [comment]
@RobLoach It is not needed, but convenient as [PSR-0 is deprecated since 2014-10](http://www.php-fig.org/psr/psr-0/).

**Pull request closed without merging**
