### PR TITLE
updated for new Types supported for Drupal.

### PR DESCRIPTION
**Pull request by miteshmap**

### CODE REVIEW

**Comment by jadb** [comment]
There are a couple Drupal related updates (i.e. #294 #273 #264 #65). Since am very unfamiliar with Drupal, if everyone who submitted could vouch for one PR and/or rebase the necessary ones, will make it that much easier to merge.

**Comment by edysmp** [comment]
All are for different reasons. #273 isn't that common, but possible and is a new theme engine. #294 desires to default all of these "things" into a contrib folder. #264 wants to add a new project classification (I'm not sure it is necessary). And #179 wants to add a sites folder.

In reality, we should continue the standard of a "contrib" folder (per #294) in each of these new types and also have a "custom" option too. An exception is for #179, where having a contrib vs custom doesn't make sense for sites.

**Comment by edysmp** [comment]
PR #294 updated for all.

**Comment by ofry** [comment]
This PR has merge conflicts.

**Comment by Seldaek** [comment]
Going to close this as I assume this is not needed anymore. If it is then it should be discussed in concert with the drupal team, as at this point so many Drupal sites are out there depending on the behavior here that I am not really comfortable changing the behavior without consulting people who are more in the know.

**Pull request closed without merging**
