### PR TITLE
Drupal site

### PR DESCRIPTION
**Pull request by davidbarratt**
This pull requests implements the feature request from #178.

### CODE REVIEW

**Comment by jadb** [comment]
Please see: https://github.com/composer/installers/pull/285#issuecomment-200423753

**Comment by CaptainQuirk** [comment]
Hi,

If I understand you correctly, rebasing would be the only thing to do to get this integrated ?

**Comment by CaptainQuirk** [comment]
That was quick ! I would be very interested to have this merged : having to fork the project or create a dummy installer just for this would be too bad !

Thanks in advance !

**Comment by CaptainQuirk** [comment]
Any news on this one ?

**Comment by CaptainQuirk** [comment]
Hi there !

It would be great if you could merge this ! Waiting for other Drupal PR to be merged doesn't seem necessary to me.

Would you care to elaborate ?

Thanks in advance

**Comment by ofry** [comment]
This PR has merge conflicts.

**Comment by Seldaek** [comment]
Going to close this as I assume this is not needed anymore. If it is then it should be discussed in concert with the drupal team, as at this point so many Drupal sites are out there depending on the behavior here that I am not really comfortable changing the behavior without consulting people who are more in the know.

**Pull request closed without merging**
