### PR TITLE
Update TastyIgniter Installer

### PR DESCRIPTION
**Pull request by sampoyigi**
This PR updates the TastyIgniter installer to use data defined under the extra property when determining the install path.

### CODE REVIEW

**Comment by sampoyigi** [comment]
Can't get the phpstan check to pass, what am I missing?

**Comment by sampoyigi** [comment]
@niksamokhvalov could you please have a look?

**Comment by niksamokhvalov** [comment]
```
Error: ] Found 2 errors                                                         
[101](https://github.com/composer/installers/runs/5038318637?check_suite_focus=true#step:7:101)

[102](https://github.com/composer/installers/runs/5038318637?check_suite_focus=true#step:7:102)
Error: Parameter #3 $subject of function preg_replace expects array|string, string|null given.
[103](https://github.com/composer/installers/runs/5038318637?check_suite_focus=true#step:7:103)
Error: Method Composer\Installers\TastyIgniterInstaller::inflectExtensionVars() should return array<string, string> but returns array<string, string|null>.
[104](https://github.com/composer/installers/runs/5038318637?check_suite_focus=true#step:7:104)
Error: Process completed with exit code 1.
```

May be you will try change phpDocs for `inflectExtensionVars()`? Returned values and phpDocs isn't compatibility.

**Comment by sampoyigi** [comment]
Thanks, got it passing now, is there anything else I can do here?

**Pull request merged**
