### PR TITLE
Add `core` to concrete5 installer

### PR DESCRIPTION
**Pull request by KorvinSzanto**
This allows us to properly install the concrete5 core via composer.

### CODE REVIEW

**Comment by fabian** [comment]
Totally in support of this, as originally proposed in https://github.com/composer/installers/pull/225. Now with the planned subtree split this seems like a good solution.

However I would propose to keep `concrete5-update` for legacy support (5.6-8.0).

**Comment by KorvinSzanto** [comment]
@fabian fine with me, do you mind submitting a pull request that adds it back to my `patch-1` branch?

**Comment by KorvinSzanto** [comment]
@fabian Actually I was able to get that added back in. Thanks!

**Comment by KorvinSzanto** [comment]
@niksamokhvalov This is good to merge, tests pass and it's just adding a core directory. This change is required for some work we are trying to do in the concrete5 core at the moment.

Thanks!

**Pull request merged**
