### PR TITLE
Remove TYPO3 Extension installers

### PR DESCRIPTION
**Pull request by astehlik**
The current version of the TYPO3CmsInstaller does not work correctly
and might confuse people.

TYPO3 CMS comes with its own installer that takes care of installing
Extensions.

### CODE REVIEW

**Comment by alcohol** [comment]
What about people using older versions of TYPO3 CMS though?

**Comment by astehlik** [comment]
The composer installers provided by TYPO3 are compatible with TYPO 6.2 LTS (the oldest supported version). Older versions (4.5) are not supported any more and do not support Composer. So I think it shouldn't be a problem.

**Comment by patkar** [comment]
It is a major breaking change in a bugfix release! We use it because with our infrastructure and internal package structure the typo3 composer installer from @helhum does not work :/

Please never remove code without major release.

**Comment by helhum** [comment]
> We use it because with our infrastructure and internal package structure the typo3 composer installer from @helhum does not work

First of all, this is not **my** installer. It is the official TYPO3 composer installer. You're better off using that one as the install code here can have unforeseeable side effects, which people regularly ran into.

This pull request was meant to avoid confusion, not to cause it. Sorry if this did not work out.

**Comment by patkar** [comment]
Doing BC breaks for the sake of avoiding confusion is the wrong way..

**Comment by helhum** [comment]
Adding a pull request does not mean, deciding on a release strategy…

**Comment by mbrodala** [comment]
I know this one is ancient but still valid. The installer solution for TYPO3 provided by `composer/installers` is not sufficient and covers only a small subset of the features `typo3/cms-composer-installers` provides.

So technically this could be removed by adding a dependency on `typo3/cms-composer-installers`; this would avoid the requirement of a major version bump. I can fully understand that this is not desirable though so a suggestion would be enough; in this case the change can only be released with a new major version.

The current situation is far from optimal since people which require `composer/installers` for other packages cannot have TYPO3 installed at the same time. Not sure how likely this is but technically there is no reason for a conflict here. There is a dedicated installer package for TYPO3 which is even maintained by TYPO3 developers and thus guaranteed to be up to date.

Maybe @bmack and @naderman could have a look at this and make a decision.

**Comment by gilbertsoft** [comment]
FYI #466 tries to solve this issue without removing the TYPO3CmsInstaller here but ofc this is a workaround only as it's really not needed here. See also the comments of @helhum in #300 .

**Pull request merged**
