### PR TITLE
Add installer for TastyIgniter extensions and themes

### PR DESCRIPTION
**Pull request by sampoyigi**

### CODE REVIEW

**Comment by sampoyigi** [comment]
Let me know if I've missed anything.

**Comment by niksamokhvalov** [comment]
@sampoyigi can you update your PR? You need to merge actual code from composer/installer and fix all tests.

**Comment by sampoyigi** [comment]
What do you mean by "merge actual code from composer/installer"?

**Comment by niksamokhvalov** [comment]
Update your branch, fix tests and open new PR, please.

**Pull request merged**
