### PR TITLE
Concrete5: Block & theme install location updates.

### PR DESCRIPTION
**Pull request by olsgreen**
Blocks & themes haven't been stored in /blocks or /themes since 5.6.x.

I've updated the installers to their relevant 5.7+ locations or /application/blocks or application/themes/ respectively.

@KorvinSzanto @aambler Any objections?

### CODE REVIEW

**Comment by olsgreen** [comment]
@Remo I think you originally added the installers? Do you mind the change to 5.7 format?

**Comment by Remo** [comment]
@olsgreen we are always creating packages if we want to reuse something. I would even be fine if concrete5.7 would have removed those two types and made packages mandatory.
The only theoretical problem I see is that it isn't backwards compatible. If someone uses ~1.0 version of this installer he would get a newer version which doesn't work with 5.6 anymore. However, since it doesn't work with 5.7 at the moment, I'd assume that everyone uses packages. If it breaks for one person he would have to specify an exact version for composer-installers. Annoying, but easy to fix.
I'd say it's good to go!

**Comment by olsgreen** [comment]
@Remo composer packages sure make life easier! It's a pain that we can't preserve backwards compatibility with 5.6.x, I can't envisage that too many people were using them within 5.6, as you say they can just freeze the version.

**Comment by olsgreen** [comment]
@notamedia Can we get this merged with the next release please. Thanks.

**Comment by niksamokhvalov** [comment]
Oh, it's not okay to break BC…

**Comment by Remo** [comment]
@niksamokhvalov not sure I understand, you're saying it's not okay, but you just merged this PR? I'd also prefer not to break anything, but I don't think it's possible without creating a new type or adding some dynamic checks in the installer. Although, looking through packagist makes me believe that I'm almost the only person using composer with concrete5.6.

**Comment by niksamokhvalov** [comment]
I merged this PR because Concrete Installer not marked as stable in README.md. But anyway, break BC is not the best practice.

> Although, looking through packagist makes me believe that I'm almost the only person using composer with concrete5.6.

It's good!

**Pull request merged**
